MovieReviewAppBackend/models.py
from flask_login import UserMixin

from . import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    reviews = db.relationship('Review', backref='user', lazy=True)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

class Review(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    review_title = db.Column(db.String(200), nullable=False)
    review_content = db.Column(db.Text, nullable=False)
    rating = db.Column(db.Integer, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    movie_id = db.Column(db.Integer, db.ForeignKey('movie.id'), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class Movie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text, nullable=False)
    image_url = db.Column(db.String(2083), nullable=False, default="/MovieReviewAppBackend/static/default.jpg")
    reviews = db.relationship('Review', backref='movie', lazy=True)

    @property
    def average_rating(self):
        total_rating = sum([review.rating for review in self.reviews])
        return round(total_rating / len(self.reviews), 1) if self.reviews else 0

    @property
    def number_of_reviews(self):
        return len(self.reviews)

MovieReviewAppBackend/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

def create_app(config_name=None):
    app = Flask(__name__)

    # Apply configuration
    if config_name:
        app.config.from_object(config_name)

    # Initialize extensions
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    # Register Blueprints (modular routing)
    from .routes import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Import models so db.create_all() knows about them
    from . import models

    return app

MovieReviewAppBackend/routes.py
from flask import Blueprint, flash, render_template, request, redirect, url_for, abort
from flask_login import login_user, login_required, current_user, logout_user
from .models import User, Movie, Review
from . import db, login_manager

main = Blueprint('main', __name__)



# ----- Index -----

@main.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main.movies'))
    return redirect(url_for('main.login'))



# -------------- Authorization routes -----------------

# Register
@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']

        if username and email and password:
            if not (len(username) >= 8):
                flash('Username must be at least 8 characters')
                return render_template('register.html')

            if '@' not in email or '.' not in email:
                flash('Please enter a valid email address')
                return render_template('register.html')

            if not (len(password) >= 8):
                flash('Password must be at least 8 characters')
                return render_template('register.html')

            new_user = User(username=username, email=email)
            new_user.set_password(password)

            db.session.add(new_user)
            db.session.commit()

            flash('Successfully registered')
            return redirect(url_for('main.login'))

        flash('Please enter all fields')
        return render_template('register.html')

    return render_template('register.html')

# Login
@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        if username and password:
            user = User.query.filter_by(username=username).first()

            if user is None:
                # User not found
                flash('User not found')
                return render_template('login.html')
            else:
                # User found
                correct_password = user.check_password(password)

                if correct_password:
                    # Correct password
                    login_user(user)

                    # flash('Logged in successfully.')

                    # next = request.args.get('next')
                    # if not url_has_allowed_host_and_scheme(next, request.host):
                    #     return abort(400)

                    return redirect('movies')
                else:
                    # Incorrect password
                    flash('Incorrect password')
                    return render_template('login.html')
        flash('Please enter all fields')

    return render_template('login.html')

# Logout
@main.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    if request.method == 'POST':
        logout_user()
        flash('You have been logged out.')
        return redirect(url_for('main.index'))

    return render_template('logout.html', url=request.referrer)

# Callback to reload the user object from the user ID stored in the session
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



# ---------------------------- Movie review routes ----------------------------------

# Browse movies
@main.route('/movies')
@login_required
def movies():
    return render_template('movies.html', Movies=Movie.query.all())

# Page for a specific movie
@main.route('/movie/<movie_id>')
@login_required
def movie(movie_id):
    selected_movie = Movie.query.get(movie_id)
    reviews = Review.query.filter_by(movie_id=movie_id).order_by(Review.id.desc()).all()

    return render_template('movie.html', movie=selected_movie, reviews=reviews)

# Create review
@main.route('/movie/<movie_id>/write-review', methods=['POST', 'GET'])
@login_required
def write_review(movie_id):
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        rating = request.form['rating']

        new_review = Review(review_title=title,
                            review_content=content,
                            rating=rating,
                            user_id=current_user.id,
                            movie_id=movie_id)

        db.session.add(new_review)

        db.session.commit()

        return redirect(url_for('main.movie', movie_id=movie_id))
    return render_template('write-review.html', Movie=Movie.query.get(movie_id))

# Delete review TODO: Revise this
@main.route('/movie/<movie_id>/delete-review/<review_id>', methods=['POST', 'GET'])
@login_required
def delete_review(movie_id, review_id):
    if not current_user == Review.query.get(review_id).user:
        flash("You can't delete this post!")
        return redirect(url_for('main.movie', movie_id=movie_id))

    if request.method == 'POST':
        # POST request deletes the review
        db.session.delete(Review.query.get(review_id))
        db.session.commit()

        # Redirect to main movie page
        return redirect(url_for('main.movie', movie_id=movie_id))

    # GET request to this route returns the 'delete review' page
    return render_template('delete-review.html', movie_id=movie_id, review_id=review_id)



# ------------ Error Handlers ----------

# 401
@main.errorhandler(401)
def unauthorized(e):
    flash("Unauthorized access!")
    return redirect(request.referrer)

MovieReviewAppBackend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>
<body>
    <div id="outer-container">
        <div id="inner-container">
            <nav class="spaced-between">
                <a href="/movies">Movies</a>
                <a href="/logout">Logout</a>
            </nav>

            <div class="page-header">
                {% block head %}{% endblock %}
            </div>

            {# Flashed messages #}
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <ul class="flashes">
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}

            <div id="main-content">
                {% block content %}{% endblock %}
            </div>

            <footer>
                <span>© 2024 brody-t</span>
            </footer>
        </div>
    </div>
</body>
</html>

MovieReviewAppBackend/templates/delete-review.html
{% extends "base.html" %}

{% block head %}
    <h1>{% block title %}Delete Review?{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div id="yes-no-container">
        {# If choose no, request to get main movie page #}
        <form class="no" method="get" action="/movie/{{ movie_id }}">
            <button type="submit">No</button>
        </form>

        {# If choose yes, request to "post" to delete review page #}
        <form class="yes" method="post" action="/movie/{{ movie_id }}/delete-review/{{ review_id }}">
            <button type="submit">Yes</button>
        </form>
    </div>
{% endblock %}

MovieReviewAppBackend/templates/login.html
{% extends "base.html" %}

{% block head %}
    <h1>{% block title %}Login{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="centered">
        <form action="/login" method="post">
            <label for="username" class="input-label">Username:</label><br>
            <input type="text" id="username" class="input-box" name="username"><br>

            <label for="password" class="input-label">Password:</label><br>
            <input type="password" id="password" class="input-box" name="password"><br>

            <div class="centered">
                <button type="submit" style="margin-top: 5pt; margin-bottom: 5pt">
                    Submit
                </button>
            </div>
        </form>
    </div>
    <div id="signup-prompt" class="centered">
        <span>Don't have an account? <a href="{{ url_for('main.register') }}">Register</a></span>
    </div>
{% endblock %}

MovieReviewAppBackend/templates/logout.html
{% extends "base.html" %}

{% block head %}
    <h1>{% block title %}Logout?{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div id="yes-no-container">
        {# If choose no, redirect to main movie page #}
        <form class="no" action={{ url }}>
            <button type="submit">No</button>
        </form>

        {# If choose yes, request to login page #}
        <form class="yes"  method="post" action="/logout">
            <button type="submit">Yes</button>
        </form>
    </div>
{% endblock %}

MovieReviewAppBackend/templates/movie.html
{% extends "base.html" %}

{% block head %}
        <h1>
            {% block title %}{{movie.title}}{% endblock %}
            <br>
            {% if movie.average_rating %}
                <span class="movie-rating">
                    {{ movie.average_rating }} <span class="star">★</span>
                </span>
            {% else %}
                <span class="movie-rating">No Rating</span>
            {% endif %}
        </h1>
{% endblock %}

{% block content %}
    <div class="centered">
        <div class="movie-description-container">
            <p class="movie-description">{{movie.description}}</p>
        </div>
    </div>

    <div class="spaced-between">
        <span class="reviews-header">Reviews</span>
        <a href="/movie/{{ movie.id }}/write-review">Write a Review</a>
    </div>

    <div id="reviews-section">
        {% for r in reviews %}
            <div class="review">
                <div class="review-header">
                    <span><strong>{{ r.review_title }}</strong></span>
                    <span>
                        {% for s in range(r.rating) %}
                            <span class="star">★</span>
                        {% endfor %}
                        {% for s in range(5-r.rating) %}
                            <span class="star">☆</span>
                        {% endfor %}
                    </span>
                </div>
                <div class="review-timestamp">{{ r.user.username }} · {{ r.updated_at }}</div>
                <div class="review-content">
                    <span>{{ r.review_content }}</span>
                    {% if r.user == current_user %}
                        <form action="/movie/{{ movie.id }}/delete-review/{{ r.id }}" method="get">
                            <button type="submit">Delete</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

MovieReviewAppBackend/templates/movies.html
{% extends "base.html" %}

{% block head %}
    <h1>{% block title %}All Movies{% endblock %}</h1>
{% endblock %}
{% block content %}
    <div class="movie-card-container">
        {% for m in Movies %}
            <a href="/movie/{{m.id}}">
                <div class="movie-card" style="background-image: url({{ m.image_url }})">
                    <div>
                        {{m.title}}
                    </div>
                    {% if m.average_rating %}
                        <span class="movie-rating">
                            {{ m.number_of_reviews }} Reviews · {{ m.average_rating }} <span class="star">★</span>
                        </span>
                    {% else %}
                        <span class="movie-rating">No Rating</span>
                    {% endif %}
                </div>
            </a>
        {% endfor %}
    </div>

{% endblock %}

MovieReviewAppBackend/templates/register.html
{% extends "base.html" %}

{% block head %}
    <h1>{% block title %}Register{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="centered">
        <form action="/register" method="post">
            <label for="username" class="input-label">Username:</label><br>
            <input type="text" id="username" class="input-box" name="username"><br>

            <label for="email" class="input-label">Email:</label><br>
            <input type="text" id="email" class="input-box" name="email"><br>

            <label for="password" class="input-label">Password:</label><br>
            <input type="password" id="password" class="input-box" name="password"><br>

            <div class="centered">
                <button type="submit" style="margin-top: 5pt; margin-bottom: 5pt">
                    Submit
                </button>
            </div>

        </form>
    </div>

    <div id="signup-prompt" class="centered">
        <span>Already have an account? <a href="{{ url_for('main.login') }}">Log In</a></span>
    </div>
{% endblock %}

MovieReviewAppBackend/templates/write-review.html
{% extends "base.html" %}

{% block head %}
    <h1>{% block title %}Write a Review · {{ Movie.title }}{% endblock %}</h1>
{% endblock %}
{% block content %}
    <div id="write-review-container">
        <form class="review-form" method="post" action="/movie/{{ Movie.id }}/write-review">
            <label for="review-title" class="input-label">Review Title:</label>
            <input type="text" id="review-title" class="input-box" name="title" required />

            <label for="review-content" class="input-label">Your Review:</label>
            <textarea id="review-content" class="input-box" name="content" rows="10" cols="30" required></textarea>

             <label for="review-rating" class="input-label">Rating (between 1 and 5):</label>
             <input type="range" id="review-rating" name="rating" min="1" max="5">

            <div class="centered">
                <button type="submit" style="width: min-content; margin-top: 5pt">
                    Submit
                </button>
            </div>
        </form>
    </div>
{% endblock %}